version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: topoDB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    container_name: nextjs_container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=topoDB
    depends_on:
      - mysql
    volumes:
      - ./nextjs:/app
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
